services:
  - type: web
    name: kukoo-2026
    runtime: node
    plan: free
    buildCommand: npm install --build-from-source
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22.14.0
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000
